blank_issues_enabled: false
contact_links:
  - name: "Support"
    url: "https://github.com/SneakyPeteMGMT/Grabbot/issues/new"
    about: "Allgemeine Fragen zum Projekt oder wenn du dir unsicher bist, welchen Template‑Typ du wählen sollst."